name: Guns
version: '${version}'
main: io.github.itzispyder.guns.Guns
api-version: '1.20'
authors: [ImproperIssues]
description: Guns

permissions:
  guns.commands.guns:
    description: Permission to run /guns
    default: op
  guns.commands.blockcollisions:
    description: Permission to check block collisions
    default: op

commands:
  guns:
    description: Edit guns and inspect info
    permission: guns.commands.guns
  blockcollisions:
    description: Check block collisions
    permission: guns.commands.blockcollisions
